# Generated by Django 2.2 on 2019-09-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_notifications', '0006_auto_20190829_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='manual',
            field=models.BooleanField(default=False, verbose_name='Tâche fermable manuellement'),
        ),
    ]
