# Generated by Django 2.2.3 on 2019-10-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_notifications', '0007_notificationtype_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actor_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anonymous text for actor'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='obj_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anonymous text for action object'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anonymous text for target'),
        ),
    ]
